Perform operations like
filtering data based on conditions, handling
missing values, and calculating summary
statistics.

In [27]:
import pandas as pd

In [28]:
data = pd.read_csv('/content/01.Data Cleaning and Preprocessing.csv')

In [29]:
data.head(5)

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
0,31-00:00,23.10,16.520,121.717,1177.607,169.805,358.282,329.545,1.443,599.253,...,67.122,329.432,303.099,175.964,1127.197,1319.039,257.325,54.612,252.077,NaN
1,31-01:00,27.60,16.810,79.022,1328.360,341.327,351.050,329.067,1.549,537.201,...,60.012,330.823,304.879,163.202,665.975,1297.317,241.182,46.603,251.406,29.11
2,31-02:00,23.19,16.709,79.562,1329.407,239.161,350.022,329.260,1.600,549.611,...,61.304,329.140,303.383,164.013,677.534,1327.072,237.272,51.795,251.335,NaN
3,31-03:00,23.60,16.478,81.011,1334.877,213.527,350.938,331.142,1.604,623.362,...,68.496,328.875,302.254,181.487,767.853,1324.461,239.478,54.846,250.312,29.02
4,31-04:00,22.90,15.618,93.244,1334.168,243.131,351.640,332.709,NaN,638.672,...,70.022,328.352,300.954,183.929,888.448,1343.424,215.372,54.186,249.916,29.01

In [30]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 324 entries, 0 to 323
Data columns (total 23 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Observation      324 non-null    object
 1   Y-Kappa          324 non-null    float64
 2   ChipRate         319 non-null    float64
 3   BF-CMratio       307 non-null    float64
 4   BlowFlow         308 non-null    float64
 5   ChipLevel4       323 non-null    float64
 6   T-upperExt-2     322 non-null    float64
 7   T-lowerExt-2     322 non-null    float64
 8   UCZAA            299 non-null    float64
 9   WhiteFlow-4      323 non-null    float64
 10  AAWhiteSt-4      173 non-null    float64
 11  AA-Wood-4        323 non-null    float64
 12  ChipMoisture-4   323 non-null    float64
 13  SteamFlow-4      323 non-null    float64
 14  Lower-HeatT-3    322 non-null    float64
 15  Upper-HeatT-3    322 non-null    float64
 16  ChipMass-4       323 non-null    float64
 17  WeakLiquorF      323 non-null    float64
 18  BlackFlow-2      322 non-null    float64
 19  WeakWashF        323 non-null    float64
 20  SteamHeatF-3     322 non-null    float64
 21  T-Top-Chips-4    323 non-null    float64
 22  SulphidityL-4    173 non-null    float64
dtypes: float64(22), object(1)
memory usage: 58.3+ KB

In [31]:
data=data[~data['BF-CMratio'].isna()]

In [32]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 307 entries, 0 to 323
Data columns (total 23 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Observation      307 non-null    object
 1   Y-Kappa          307 non-null    float64
 2   ChipRate         304 non-null    float64
 3   BF-CMratio       307 non-null    float64
 4   BlowFlow         307 non-null    float64
 5   ChipLevel4       306 non-null    float64
 6   T-upperExt-2     307 non-null    float64
 7   T-lowerExt-2     307 non-null    float64
 8   UCZAA            283 non-null    float64
 9   WhiteFlow-4      306 non-null    float64
 10  AAWhiteSt-4      163 non-null    float64
 11  AA-Wood-4        306 non-null    float64
 12  ChipMoisture-4   306 non-null    float64
 13  SteamFlow-4      306 non-null    float64
 14  Lower-HeatT-3    307 non-null    float64
 15  Upper-HeatT-3    307 non-null    float64
 16  ChipMass-4       306 non-null    float64
 17  WeakLiquorF      307 non-null    float64
 18  BlackFlow-2      307 non-null    float64
 19  WeakWashF        307 non-null    float64
 20  SteamHeatF-3     307 non-null    float64
 21  T-Top-Chips-4    306 non-null    float64
 22  SulphidityL-4    163 non-null    float64
dtypes: float64(22), object(1)
memory usage: 57.6+ KB

In [33]:
data=data[~data['UCZAA'].isna()]

In [34]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 283 entries, 0 to 323
Data columns (total 23 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Observation      283 non-null    object
 1   Y-Kappa          283 non-null    float64
 2   ChipRate         283 non-null    float64
 3   BF-CMratio       283 non-null    float64
 4   BlowFlow         283 non-null    float64
 5   ChipLevel4       282 non-null    float64
 6   T-upperExt-2     283 non-null    float64
 7   T-lowerExt-2     283 non-null    float64
 8   UCZAA            283 non-null    float64
 9   WhiteFlow-4      282 non-null    float64
 10  AAWhiteSt-4      141 non-null    float64
 11  AA-Wood-4        282 non-null    float64
 12  ChipMoisture-4   282 non-null    float64
 13  SteamFlow-4      282 non-null    float64
 14  Lower-HeatT-3    283 non-null    float64
 15  Upper-HeatT-3    283 non-null    float64
 16  ChipMass-4       282 non-null    float64
 17  WeakLiquorF      283 non-null    float64
 18  BlackFlow-2      283 non-null    float64
 19  WeakWashF        283 non-null    float64
 20  SteamHeatF-3     283 non-null    float64
 21  T-Top-Chips-4    282 non-null    float64
 22  SulphidityL-4    141 non-null    float64
dtypes: float64(22), object(1)
memory usage: 53.1+ KB

In [35]:
data['SulphidityL-4 ']=data['SulphidityL-4 '].astype(object)
data=data[~data['SulphidityL-4 '].isna()]

In [36]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 141 entries, 1 to 322
Data columns (total 23 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Observation      141 non-null    object
 1   Y-Kappa          141 non-null    float64
 2   ChipRate         141 non-null    float64
 3   BF-CMratio       141 non-null    float64
 4   BlowFlow         141 non-null    float64
 5   ChipLevel4       141 non-null    float64
 6   T-upperExt-2     141 non-null    float64
 7   T-lowerExt-2     141 non-null    float64
 8   UCZAA            141 non-null    float64
 9   WhiteFlow-4      141 non-null    float64
 10  AAWhiteSt-4      141 non-null    float64
 11  AA-Wood-4        141 non-null    float64
 12  ChipMoisture-4   141 non-null    float64
 13  SteamFlow-4      141 non-null    float64
 14  Lower-HeatT-3    141 non-null    float64
 15  Upper-HeatT-3    141 non-null    float64
 16  ChipMass-4       141 non-null    float64
 17  WeakLiquorF      141 non-null    float64
 18  BlackFlow-2      141 non-null    float64
 19  WeakWashF        141 non-null    float64
 20  SteamHeatF-3     141 non-null    float64
 21  T-Top-Chips-4    141 non-null    float64
 22  SulphidityL-4    141 non-null    object
dtypes: float64(21), object(2)
memory usage: 26.4+ KB

In [37]:
data['SulphidityL-4 ']=data['SulphidityL-4 '].astype(float)

In [38]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 141 entries, 1 to 322
Data columns (total 23 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Observation      141 non-null    object
 1   Y-Kappa          141 non-null    float64
 2   ChipRate         141 non-null    float64
 3   BF-CMratio       141 non-null    float64
 4   BlowFlow         141 non-null    float64
 5   ChipLevel4       141 non-null    float64
 6   T-upperExt-2     141 non-null    float64
 7   T-lowerExt-2     141 non-null    float64
 8   UCZAA            141 non-null    float64
 9   WhiteFlow-4      141 non-null    float64
 10  AAWhiteSt-4      141 non-null    float64
 11  AA-Wood-4        141 non-null    float64
 12  ChipMoisture-4   141 non-null    float64
 13  SteamFlow-4      141 non-null    float64
 14  Lower-HeatT-3    141 non-null    float64
 15  Upper-HeatT-3    141 non-null    float64
 16  ChipMass-4       141 non-null    float64
 17  WeakLiquorF      141 non-null    float64
 18  BlackFlow-2      141 non-null    float64
 19  WeakWashF        141 non-null    float64
 20  SteamHeatF-3     141 non-null    float64
 21  T-Top-Chips-4    141 non-null    float64
 22  SulphidityL-4    141 non-null    float64
dtypes: float64(22), object(1)
memory usage: 26.4+ KB

In [39]:
data

,Observation,Y-Kappa,ChipRate,BF-CMratio,BlowFlow,ChipLevel4,T-upperExt-2,T-lowerExt-2,UCZAA,WhiteFlow-4,...,SteamFlow-4,Lower-HeatT-3,Upper-HeatT-3,ChipMass-4,WeakLiquorF,BlackFlow-2,WeakWashF,SteamHeatF-3,T-Top-Chips-4,SulphidityL-4
1,31-01:00,27.60,16.810,79.022,1328.360,341.327,351.050,329.067,1.549,537.201,...,60.012,330.823,304.879,163.202,665.975,1297.317,241.182,46.603,251.406,29.110
3,31-03:00,23.60,16.478,81.011,1334.877,213.527,350.938,331.142,1.604,623.362,...,68.496,328.875,302.254,181.487,767.853,1324.461,239.478,54.846,250.312,29.020
5,1-08:00,14.23,15.350,85.518,1171.604,198.538,344.014,325.195,1.436,628.245,...,65.225,322.103,298.517,165.814,826.243,907.641,595.875,52.807,249.580,30.340
7,31-06:00,22.65,14.100,91.887,1307.852,288.989,352.321,331.162,1.468,625.549,...,71.298,329.662,301.539,179.886,837.178,1315.111,234.047,53.805,249.971,29.220
9,31-08:00,24.70,13.850,96.208,1334.892,362.511,352.372,327.358,1.515,553.172,...,64.249,332.264,305.419,166.120,909.810,1318.725,180.375,48.842,251.121,29.210
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312,31-10:00,24.40,14.117,85.998,1330.104,394.234,348.089,319.027,1.429,540.558,...,62.179,329.831,302.652,163.258,827.107,1312.372,132.163,49.446,251.406,29.292
317,4-16:00,17.80,16.625,78.367,1276.082,202.744,360.127,329.266,1.488,698.486,...,75.296,321.658,297.088,180.438,1017.333,1052.785,433.089,54.675,251.747,30.320
319,10-16:00,23.75,12.667,93.450,1178.252,276.955,347.286,310.970,1.523,513.956,...,61.141,330.117,304.006,148.174,1027.201,1357.271,381.643,45.264,252.947,30.860
320,9-19:00,19.80,12.558,94.352,1184.119,297.071,399.135,319.576,1.451,570.058,...,67.667,330.848,304.616,165.178,906.962,1311.177,25.494,50.528,252.092,30.700
322,9-21:00,24.32,13.083,88.910,1192.879,318.006,364.081,308.559,1.523,504.852,...,61.054,327.346,304.363,147.589,804.423,1320.225,0.000,43.725,253.176,31.130

In [40]:
data.to_csv('Cleaned_data.csv')